package com.example.accessingdatamysql.api.controllers;

import com.example.accessingdatamysql.dataAccess.abstracts.DhtDao;
import com.example.accessingdatamysql.entity.concrate.sensor.Dht11;
import com.example.accessingdatamysql.entity.concrate.sensor.User;
import com.example.accessingdatamysql.dataAccess.abstracts.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Date;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/api/dht") // This means URL's start with /demo (after Application path)
@Repository
public class Dht11TempatureController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DhtDao _dhtDao;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String heat
            , @RequestParam String humidity, @RequestParam Date date) {

        Dht11 dht11 = new Dht11();
        dht11.setHeat(heat);
        dht11.setHumidity(humidity);
        dht11.setDate(date);
        _dhtDao.save(dht11);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Dht11> getAllDhtData() {
        // This returns a JSON or XML with the users
        return _dhtDao.findAll();
    }
}
